# Generated by Django 5.1.1 on 2024-09-23 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aitutor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitutorchat',
            name='subject',
            field=models.CharField(choices=[('IOT', 'Iot'), ('CODING', 'Coding'), ('STEM', 'Stem'), ('ROBOTICS', 'Robotics'), ('AI', 'Ai')], default='IOT', max_length=9),
            preserve_default=False,
        ),
    ]
