# Generated by Django 5.1.1 on 2024-09-10 11:30

import django.db.models.deletion
import libres.checker
import libres.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('name_slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('icon', models.ImageField(upload_to='categories/')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('title_slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('thumb', models.ImageField(blank=True, default='static/img/default.jpg', null=True, upload_to='sub_categories/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_subcat', to='libres.category')),
            ],
            options={
                'verbose_name': 'Sub category',
                'verbose_name_plural': 'Sub Categories',
            },
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('uploaded_file', models.FileField(upload_to=libres.models.upload_file_to, validators=[libres.checker.validate_file_extension])),
                ('media_type', models.CharField(choices=[('PDF', 'pdf'), ('VIDEO', 'video'), ('WORD', 'word')], default='PDF', max_length=8)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_cat', to='libres.subcategory')),
            ],
            options={
                'verbose_name': 'file upload',
                'verbose_name_plural': 'File Uploads',
            },
        ),
    ]
